---
development:
  dialect: postgres
  database: go-ddd-boilerplate_test
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: go-ddd-boilerplate_test
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

production:
  dialect: postgres
  database: go-ddd-boilerplate_production
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5
